# Created with YamlCreate.ps1 v2.2.2 $debug=NVS0.CRLF.5-1-22000-1335.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: Colemak.Colemak
PackageVersion: "1.1"
PackageLocale: en-US
Publisher: Colemak
PublisherUrl: https://colemak.com/
# PublisherSupportUrl:
# PrivacyUrl:
# Author:
PackageName: Colemak
PackageUrl: https://colemak.com/Windows
License: Proprietary
# LicenseUrl:
# Copyright:
# CopyrightUrl:
ShortDescription: Colemak keyboard layout
# Description:
Moniker: colemak
Tags:
- colemak
- keyboard
- layout
# Agreements:
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.4.0
